name = "Khovanov"
uuid = "033b080b-81cb-4a7b-845e-e0156c9eb54a"
authors = ["Taketo Sano <taketo1024@gmail.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
